import { JobData } from "@/types";
import { SalaryCurrency } from "../enums/currency.enum";

export const INITIAL_JOB_DATA: JobData = {
  companyId: null,
  title: "",
  jobIndustryId: null,
  jobSpecialityId: null,
  jobCategoryId: null,
  jobCareerLevelId: null,
  jobEmploymentTypeId: null,
  jobWorkPlace: null,
  gender: null,
  minAge: null,
  maxAge: null,
  educationLevel: null,
  country: {
    code: "",
    name: "",
  },
  state: null,
  // state: {
  //   code: "",
  //   name: "",
  // },
  city: "",
  maxExpYears: null,
  minExpYears: null,
  hideSalary: true,
  salaryRangeStart: null,
  salaryRangeEnd: null,
  salaryCurrency: SalaryCurrency.USD,
  availableVacancies: 1,
  description: "<p></p>",
  requirements: "<p></p>",
  salaryDetails: null,
  keywords: [],
  skills: [],
  questions: [],
  showCompany: true,
  recieveEmails: true,
  jobEmail: null,
  draft: false,
  active: true,
  closed: false,
  startDateType: null,
  validTo: null,
  jobCareerLevel: null,
  jobCategory: null,
  jobIndustry: null,
  jobSpeciality: null,
  jobEmploymentType: null,
  created_at: "",
  updated_at: "",
  id: "",
};
