import { InvoiceType } from "@/types/finance";

export const INVOICES_DATA: InvoiceType[] = [
  {
    id: "INV_2025_001",
    created_at: "2025-01-15T10:30:00Z",
    due_date: "2025-02-15T10:30:00Z",
    created_by: {
      id: "ADMIN_001",
      image: "https://i.pravatar.cc/100?img=1",
      name: "Alice Johnson",
      role: "Admin",
    },
    isCreatedBySystem: false,
    type: "subscription",
    payment_method: "credit_card",
    status: "paid",
    payment_type: "recurring",
    employer: {
      id: "EMP_001",
      image: "https://i.pravatar.cc/100?img=2",
      username: "tech_corp",
      name: "Tech Corp Ltd.",
    },
    items: [
      {
        id: "ITEM_001",
        name: "Pro Subscription Plan",
        description: "Monthly subscription for Pro plan",
        price: 100,
        quantity: 1,
        total: 100,
      },
      {
        id: "ITEM_002",
        name: "VAT",
        description: "Value Added Tax 20%",
        price: 20,
        quantity: 1,
        total: 20,
      },
    ],
    currency: "EGP",
    subtotal: 100,
    discount: 0,
    tax: 20,
    total: 120,
  },
  {
    id: "INV_2025_002",
    created_at: "2025-02-01T09:00:00Z",
    due_date: "2025-03-01T09:00:00Z",
    created_by: {
      id: "SYS",
      image: "",
      name: "System",
      role: "System",
    },
    isCreatedBySystem: true,
    type: "add-on",
    payment_method: null,
    status: "pending",
    payment_type: "one-time",
    employer: {
      id: "EMP_002",
      image: "https://i.pravatar.cc/100?img=3",
      username: "green_solutions",
      name: "Green Solutions",
    },
    items: [
      {
        id: "ITEM_003",
        name: "Extra Storage",
        description: "Additional 50GB storage",
        price: 50,
        quantity: 1,
        total: 50,
      },
    ],
    currency: "EGP",
    subtotal: 50,
    discount: 0,
    tax: 0,
    total: 50,
  },
  {
    id: "INV_2025_003",
    created_at: "2025-02-10T14:20:00Z",
    due_date: "2025-03-10T14:20:00Z",
    created_by: {
      id: "ADMIN_002",
      image: "https://i.pravatar.cc/100?img=4",
      name: "Michael Lee",
      role: "Finance Manager",
    },
    isCreatedBySystem: false,
    type: "subscription",
    status: "overdue",
    payment_type: "recurring",
    employer: {
      id: "EMP_003",
      image: "https://i.pravatar.cc/100?img=5",
      username: "smart_retail",
      name: "Smart Retail Inc.",
    },
    items: [
      {
        id: "ITEM_004",
        name: "Enterprise Subscription",
        description: "Quarterly subscription for Enterprise plan",
        price: 200,
        quantity: 1,
        total: 200,
      },
      {
        id: "ITEM_005",
        name: "Service Tax",
        description: "Service tax 5%",
        price: 10,
        quantity: 1,
        total: 10,
      },
    ],
    currency: "EGP",
    subtotal: 200,
    discount: 0,
    tax: 10,
    total: 210,
  },
  {
    id: "INV_2025_004",
    created_at: "2025-03-01T08:15:00Z",
    due_date: "2025-04-01T08:15:00Z",
    created_by: {
      id: "SYS",
      image: "",
      name: "System",
      role: "System",
    },
    isCreatedBySystem: true,
    type: "subscription",
    status: "canceled",
    payment_type: "recurring",
    employer: {
      id: "EMP_004",
      image: "https://i.pravatar.cc/100?img=6",
      username: "blue_media",
      name: "Blue Media Group",
    },
    items: [
      {
        id: "ITEM_006",
        name: "Basic Subscription Plan",
        description: "Monthly subscription for Basic plan",
        price: 95,
        quantity: 1,
        total: 95,
      },
    ],
    currency: "EGP",
    subtotal: 95,
    discount: 0,
    tax: 0,
    total: 95,
  },
  {
    id: "INV_2025_005",
    created_at: "2025-03-05T12:45:00Z",
    due_date: "2025-04-05T12:45:00Z",
    created_by: {
      id: "ADMIN_003",
      image: "https://i.pravatar.cc/100?img=7",
      name: "Sarah Williams",
      role: "Accountant",
    },
    isCreatedBySystem: false,
    type: "add-on",
    payment_method: "stripe",
    status: "paid",
    payment_type: "one-time",
    employer: {
      id: "EMP_005",
      image: "https://i.pravatar.cc/100?img=8",
      username: "future_health",
      name: "Future Health Co.",
    },
    items: [
      {
        id: "ITEM_007",
        name: "Custom Analytics Report",
        description: "One-time analytics report package",
        price: 150,
        quantity: 1,
        total: 150,
      },
      {
        id: "ITEM_008",
        name: "Processing Fee",
        description: "Additional service charge",
        price: 30,
        quantity: 1,
        total: 30,
      },
    ],
    currency: "EGP",
    subtotal: 150,
    discount: 0,
    tax: 30,
    total: 180,
  },
];
