// import { Notification } from "@/types";
// import { NotificationEnum } from "./enums/notifications.enum";

// export const dummyNotifications: Notification[] = [
//   // Job Seeker Notifications
//   {
//     id: "notif_100001",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.NEW_JOB_MATCH,
//     title: "New Job Matches Your Profile",
//     message:
//       "New Software Engineer role at TechCorp matches your profile! Apply now.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1001",
//       actionUrl: "/jobs/job_1001",
//       imageUrl: "https://via.placeholder.com/60?text=TechCorp",
//       companyName: "TechCorp",
//       jobTitle: "Software Engineer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },

//   {
//     id: "notif_100005",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.APPLICATION_SUBMITTED,
//     title: "Application Submitted",
//     message:
//       "Your application for Graphic Designer at CreativeCo has been submitted.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1005",
//       applicationId: "app_5001",
//       actionUrl: "/applications/app_5001",
//       imageUrl: "https://via.placeholder.com/60?text=CreativeCo",
//       companyName: "CreativeCo",
//       jobTitle: "Graphic Designer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_100006",
//     userId: "seeker_001",
//     senderId: "employer_101",
//     type: NotificationEnum.APPLICATION_VIEWED,
//     title: "Your Application Was Viewed",
//     message: "Your application for Web Developer at TechTrend has been viewed.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1006",
//       applicationId: "app_5002",
//       actionUrl: "/applications/app_5002",
//       imageUrl: "https://via.placeholder.com/60?text=TechTrend",
//       companyName: "TechTrend",
//       jobTitle: "Web Developer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_100007",
//     userId: "seeker_001",
//     senderId: "employer_102",
//     type: NotificationEnum.APPLICATION_SHORTLISTED,
//     title: "Application Shortlisted",
//     message:
//       "Congratulations! You've been shortlisted for the Analyst role at FinanceCorp.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1007",
//       applicationId: "app_5003",
//       actionUrl: "/applications/app_5003",
//       imageUrl: "https://via.placeholder.com/60?text=FinanceCorp",
//       companyName: "FinanceCorp",
//       jobTitle: "Analyst",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   // {
//   //   id: "notif_100008",
//   //   userId: "seeker_001",
//   //   senderId: "employer_103",
//   //   type: NotificationEnum.APPLICATION_REJECTED,
//   //   title: "Application Not Selected",
//   //   message:
//   //     "Thank you for applying to Sales Manager at RetailCo. Unfortunately, you were not selected.",
//   //   isRead: false,
//   //   metadata: {
//   //     jobId: "job_1008",
//   //     applicationId: "app_5004",
//   //     actionUrl: "/applications/app_5004",
//   //     imageUrl: "https://via.placeholder.com/60?text=RetailCo",
//   //     companyName: "RetailCo",
//   //     jobTitle: "Sales Manager",
//   //   },
//   //   createdAt: "2025-05-31T13:21:00Z",
//   //   expiresAt: null,
//   // },
//   {
//     id: "notif_100009",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.APPLICATION_WITHDRAWN,
//     title: "Application Withdrawn",
//     message: "You’ve withdrawn your application for HR Specialist at PeopleCo.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1009",
//       applicationId: "app_5005",
//       actionUrl: "/applications/app_5005",
//       imageUrl: "https://via.placeholder.com/60?text=PeopleCo",
//       companyName: "PeopleCo",
//       jobTitle: "HR Specialist",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   // {
//   //   id: "notif_100010",
//   //   userId: "seeker_001",
//   //   senderId: "employer_104",
//   //   type: NotificationEnum.HIRED,
//   //   title: "Congratulations, You're Hired!",
//   //   message:
//   //     "Congratulations! You’ve been hired for the Software Engineer role at CodeZap!",
//   //   isRead: false,
//   //   metadata: {
//   //     jobId: "job_1010",
//   //     applicationId: "app_5006",
//   //     actionUrl: "/jobs/job_1010",
//   //     imageUrl: "https://via.placeholder.com/60?text=CodeZap",
//   //     companyName: "CodeZap",
//   //     jobTitle: "Software Engineer",
//   //   },
//   //   createdAt: "2025-05-31T13:21:00Z",
//   //   expiresAt: null,
//   // },
//   {
//     id: "notif_100011",
//     userId: "seeker_001",
//     senderId: "employer_105",
//     type: NotificationEnum.NEW_MESSAGE,
//     title: "New Message from Employer",
//     message:
//       "New message from TechTrend regarding your application for UI Designer.",
//     isRead: false,
//     metadata: {
//       jobId: "job_1011",
//       actionUrl: "/messages/employer_105",
//       imageUrl: "https://via.placeholder.com/60?text=TechTrend",
//       companyName: "TechTrend",
//       jobTitle: "UI Designer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_100012",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.PROFILE_INCOMPLETE,
//     title: "Complete Your Profile 40% left",
//     message: "Complete your profile to improve your job match score!",
//     isRead: false,
//     metadata: {
//       percentage: 60,
//       actionUrl: "/profile/edit",
//       imageUrl: "https://via.placeholder.com/60?text=Profile",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },
//   {
//     id: "notif_100015",
//     userId: "seeker_001",
//     senderId: "admin_001",
//     type: NotificationEnum.ACCOUNT_SUSPENSION_WARNING,
//     title: "Account Suspension Warning",
//     message:
//       "Your account is at risk of suspension due to incomplete profile details.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/profile/edit",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-07T13:21:00Z",
//   },
//   {
//     id: "notif_100016",
//     userId: "seeker_001",
//     senderId: "admin_001",
//     type: NotificationEnum.ACCOUNT_SUSPENDED,
//     title: "Account Suspended",
//     message:
//       "Your account has been suspended for violating platform policies. Contact support.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/support",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_100017",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.PASSWORD_RESET,
//     title: "Password Reset Requested",
//     message:
//       "A password reset was requested for your account. Click here to reset.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/reset-password",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-01T13:21:00Z",
//   },
//   {
//     id: "notif_100018",
//     userId: "seeker_001",
//     senderId: null,
//     type: NotificationEnum.NOTIFICATION_PREFERENCES_UPDATED,
//     title: "Notification Preferences Updated",
//     message: "Your notification preferences have been updated successfully.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/settings/notifications",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_100019",
//     userId: "seeker_001",
//     senderId: "admin_001",
//     type: NotificationEnum.PLATFORM_MAINTENANCE,
//     title: "Platform Maintenance Scheduled",
//     message:
//       "JobFinder Pro will be undergoing maintenance on June 1, 2025, from 2 AM to 4 AM.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/announcements",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-01T04:00:00Z",
//   },
//   {
//     id: "notif_100020",
//     userId: "seeker_001",
//     senderId: "admin_001",
//     type: NotificationEnum.NEW_FEATURE,
//     title: "New Feature Available",
//     message:
//       "Introducing our new resume builder! Create a standout resume today.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/resume-builder",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },
//   {
//     id: "notif_100021",
//     userId: "seeker_001",
//     senderId: "admin_001",
//     type: NotificationEnum.POLICY_UPDATE,
//     title: "Policy Update",
//     message: "We’ve updated our privacy policy. Review the changes here.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/policies",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },

//   // Employer Notifications
//   {
//     id: "notif_200001",
//     userId: "employer_101",
//     senderId: null,
//     type: NotificationEnum.JOB_SUBMITTED,
//     title: "Job Posting Submitted",
//     message:
//       "Your Software Developer job posting has been submitted for approval.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2001",
//       actionUrl: "/jobs/job_2001",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Software Developer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200002",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.JOB_APPROVED,
//     title: "Job Posting Approved",
//     message: "Your Data Scientist job posting is now live on JobFinder Pro!",
//     isRead: false,
//     metadata: {
//       jobId: "job_2002",
//       actionUrl: "/jobs/job_2002",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Data Scientist",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200003",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.JOB_REJECTED,
//     title: "Job Posting Not Approved",
//     message:
//       "Your job posting was not approved. Please clarify salary details and resubmit.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2003",
//       actionUrl: "/jobs/job_2003/edit",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Unknown",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },

//   {
//     id: "notif_200456",
//     userId: "employer_101",
//     senderId: null,
//     type: NotificationEnum.JOB_DRAFT,
//     title: "Incomplete Job Posting",
//     message: "Your job posting is still in draft. Complete and publish it to start receiving applications.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2006",
//       actionUrl: "/jobs/job_2006/edit",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Product Manager",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200005",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.JOB_FLAGGED,
//     title: "Job Posting Flagged",
//     message:
//       "Your Sales Associate job posting has been flagged for review. Contact support.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2005",
//       actionUrl: "/support",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Sales Associate",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },

//   {
//     id: "notif_200007",
//     userId: "employer_101",
//     senderId: "seeker_001",
//     type: NotificationEnum.NEW_APPLICATION,
//     title: "New Application Received",
//     message:
//       "A new candidate applied for your Software Engineer role. Review now.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2007",
//       applicationId: "app_6001",
//       actionUrl: "/applications/app_6001",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Software Engineer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200008",
//     userId: "employer_101",
//     senderId: "seeker_002",
//     type: NotificationEnum.APPLICATION_WITHDRAWN,
//     title: "Candidate Withdrawn",
//     message:
//       "A candidate has withdrawn their application for your Project Manager role.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2008",
//       applicationId: "app_6002",
//       actionUrl: "/applications/app_6002",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Project Manager",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200011",
//     userId: "employer_101",
//     senderId: "seeker_004",
//     type: NotificationEnum.NEW_MESSAGE,
//     title: "New Message from Candidate",
//     message: "New message from Sarah Lee regarding the HR Specialist role.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2011",
//       actionUrl: "/messages/seeker_004",
//       imageUrl: "https://via.placeholder.com/60?text=SarahLee",
//       companyName: "JobFinder Pro",
//       jobTitle: "HR Specialist",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200012",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.ACCOUNT_MANAGER_ASSIGNED,
//     title: "Account Manager Assigned",
//     message:
//       "Jane Doe has been assigned as your account manager. Contact her for support.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/support",
//       imageUrl: "https://via.placeholder.com/60?text=Support",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_201212",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.RECOMMENDED_LIST_ADDED,
//     title: "New Recommended Candidates",
//     message: "We've added 5 new candidates to your recommended list for the Senior Developer position.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/recommended-candidates",
//       imageUrl: "https://via.placeholder.com/60?text=Recommendations",
//       jobTitle: "Senior Developer",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200013",
//     userId: "employer_101",
//     senderId: null,
//     type: NotificationEnum.PROFILE_INCOMPLETE,
//     title: "Complete Your Profile 55%",
//     message: "Complete your company profile to attract more candidates!",
//     isRead: false,
//     metadata: {
//       percentage: 45,
//       actionUrl: "/profile/edit",
//       imageUrl: "https://via.placeholder.com/60?text=Profile",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },
//   {
//     id: "notif_200014",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.PROFILE_APPROVED,
//     title: "Profile Approved",
//     message: "Your employer profile has been approved. Start posting jobs now!",
//     isRead: false,
//     metadata: {
//       actionUrl: "/jobs/create",
//       imageUrl: "https://via.placeholder.com/60?text=Profile",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200015",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.PROFILE_REJECTED,
//     title: "Profile Not Approved",
//     message:
//       "Your profile was not approved. Please verify company details and resubmit.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/profile/edit",
//       imageUrl: "https://via.placeholder.com/60?text=Profile",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200016",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.ACCOUNT_SUSPENSION_WARNING,
//     title: "Account Suspension Warning",
//     message: "Your account is at risk of suspension due to unverified details.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/profile/edit",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-07T13:21:00Z",
//   },
//   {
//     id: "notif_200017",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.ACCOUNT_SUSPENDED,
//     title: "Account Suspended",
//     message:
//       "Your account has been suspended for violating platform policies. Contact support.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/support",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200018",
//     userId: "employer_101",
//     senderId: null,
//     type: NotificationEnum.PAYMENT_ISSUE,
//     title: "Payment Issue",
//     message:
//       "Your payment for job posting boost failed. Update your payment method.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/settings/billing",
//       imageUrl: "https://via.placeholder.com/60?text=Account",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-07T13:21:00Z",
//   },
//   {
//     id: "notif_200019",
//     userId: "employer_101",
//     senderId: null,
//     type: NotificationEnum.NOTIFICATION_PREFERENCES_UPDATED,
//     title: "Notification Preferences Updated",
//     message: "Your notification preferences have been updated successfully.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/settings/notifications",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_200020",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.PLATFORM_MAINTENANCE,
//     title: "Platform Maintenance Scheduled",
//     message:
//       "JobFinder Pro will be undergoing maintenance on June 1, 2025, from 2 AM to 4 AM.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/announcements",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-01T04:00:00Z",
//   },
//   {
//     id: "notif_200021",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.NEW_FEATURE,
//     title: "New Feature Available",
//     message: "New candidate filtering tools are now available! Try them today.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/candidate-search",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },
//   {
//     id: "notif_200022",
//     userId: "employer_101",
//     senderId: "admin_001",
//     type: NotificationEnum.POLICY_UPDATE,
//     title: "Policy Update",
//     message: "We’ve updated our employer terms. Review the changes here.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/policies",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },

//   // Admin Notifications
//   {
//     id: "notif_200006",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.LOW_APPLICATIONS,
//     title: "Low Application Alert",
//     message:
//       "Your Analyst role has low applications. Try updating the description or boosting visibility.",
//     isRead: false,
//     metadata: {
//       jobId: "job_2006",
//       actionUrl: "/jobs/job_2006/edit",
//       imageUrl: "https://via.placeholder.com/60?text=JobFinder",
//       companyName: "JobFinder Pro",
//       jobTitle: "Analyst",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-30T13:21:00Z",
//   },
//   {
//     id: "notif_300001",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.USER_REPORTED,
//     title: "User Reported",
//     message: "Employer BrandCo has been reported for suspicious job postings.",
//     isRead: false,
//     metadata: {
//       userId: "employer_102",
//       actionUrl: "/admin/users/employer_102",
//       imageUrl: "https://via.placeholder.com/60?text=BrandCo",
//       companyName: "BrandCo",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300002",
//     userId: "admin_001",
//     senderId: "seeker_001",
//     type: NotificationEnum.ACCOUNT_SUSPENSION_REQUEST,
//     title: "Account Suspension Review Request",
//     message: "Jane Smith has requested a review of their suspended account.",
//     isRead: false,
//     metadata: {
//       userId: "seeker_001",
//       actionUrl: "/admin/users/seeker_001",
//       imageUrl: "https://via.placeholder.com/60?text=JaneSmith",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300003",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.BULK_ACTION_COMPLETED,
//     title: "Bulk Action Completed",
//     message: "Bulk export of 100 user profiles has been completed.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/reports",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300004",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.JOB_PENDING_APPROVAL,
//     title: "New Job Posting Pending Approval",
//     message:
//       "New job posting by DataCorp for Analyst role is pending approval.",
//     isRead: false,
//     metadata: {
//       jobId: "job_3001",
//       actionUrl: "/admin/jobs/job_3001",
//       imageUrl: "https://via.placeholder.com/60?text=DataCorp",
//       companyName: "DataCorp",
//       jobTitle: "Analyst",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300005",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.JOB_REPORTED,
//     title: "Job Posting Reported",
//     message:
//       "Sales Associate job by RetailCo has been reported for unclear requirements.",
//     isRead: false,
//     metadata: {
//       jobId: "job_3002",
//       actionUrl: "/admin/jobs/job_3002",
//       imageUrl: "https://via.placeholder.com/60?text=RetailCo",
//       companyName: "RetailCo",
//       jobTitle: "Sales Associate",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300006",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.JOB_AUTO_FLAGGED,
//     title: "Job Posting Auto-Flagged",
//     message: "Marketing Manager job by AdCo was auto-flagged for keyword spam.",
//     isRead: false,
//     metadata: {
//       jobId: "job_3003",
//       actionUrl: "/admin/jobs/job_3003",
//       imageUrl: "https://via.placeholder.com/60?text=AdCo",
//       companyName: "AdCo",
//       jobTitle: "Marketing Manager",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300007",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.PLATFORM_ISSUE,
//     title: "Platform Issue Detected",
//     message: "Platform outage detected. Technical team has been notified.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/status",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300008",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.HIGH_USER_ACTIVITY,
//     title: "High User Activity Alert",
//     message: "50% increase in new user registrations detected today.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/analytics",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-07T13:21:00Z",
//   },
//   {
//     id: "notif_300009",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.LOW_ENGAGEMENT,
//     title: "Low Engagement Alert",
//     message: "Job applications dropped by 30% this week. Review analytics.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/analytics",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: "2025-06-07T13:21:00Z",
//   },
//   {
//     id: "notif_300010",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.ANALYTICS_REPORT,
//     title: "Analytics Report Ready",
//     message: "Monthly user growth and job performance report is ready.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/reports",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300011",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.BROADCAST_SENT,
//     title: "Broadcast Message Sent",
//     message: "Your maintenance alert was sent to all users.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/messages",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300012",
//     userId: "admin_001",
//     senderId: null,
//     type: NotificationEnum.TARGETED_NOTIFICATION_SENT,
//     title: "Targeted Notification Sent",
//     message: "Your message to inactive job seekers was sent successfully.",
//     isRead: false,
//     metadata: {
//       actionUrl: "/admin/messages",
//       imageUrl: "https://via.placeholder.com/60?text=System",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
//   {
//     id: "notif_300013",
//     userId: "admin_001",
//     senderId: "seeker_001",
//     type: NotificationEnum.FEEDBACK_RECEIVED,
//     title: "User Feedback Received",
//     message:
//       "Job seeker Alex Brown submitted feedback about the resume builder.",
//     isRead: false,
//     metadata: {
//       userId: "seeker_001",
//       actionUrl: "/admin/feedback",
//       imageUrl: "https://via.placeholder.com/60?text=AlexBrown",
//     },
//     createdAt: "2025-05-31T13:21:00Z",
//     expiresAt: null,
//   },
// ];
