import { RoleBasedLinks } from "@/types";
import {
  BusinessOutlined,
  DescriptionOutlined,
  FolderOutlined,
  HelpOutline,
  HomeOutlined,
  MessageOutlined,
  NewspaperOutlined,
  NotificationsActiveOutlined,
  PaidOutlined,
  PostAddOutlined,
  Search,
  SettingsOutlined,
  WorkOutline,
} from "@mui/icons-material";
import {
  BookMarked,
  CreditCard,
  FilePlus2,
  GraduationCap,
  Newspaper,
  UserCog,
  Settings,
  BarChart3,
  Megaphone,
  Plus,
  ToolCase,
} from "lucide-react";
import { Permission_Keys } from "./enums/Permission_Keys.enum";

export const roleBasedSideBarLinks: RoleBasedLinks = {
  admin: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
      permissions: [],
    },
    {
      id: 1,
      label: "Dashboard",
      icon: HomeOutlined,
      path: "/admin/dashboard",
      pattern: "/admin/dashboard/*",
      permissions: [Permission_Keys.Admin_Jobs_ViewJob],
    },
    {
      id: 21,
      label: "Employers",
      icon: WorkOutline,
      path: "/admin/employers",
      pattern: "/admin/employers/*",
      type: "supLink",
      permissions: [
        Permission_Keys.Admin_Employers_AccountManagement_ViewEmployerProfile,
      ],
    },
    {
      id: 22,
      label: "Job Seekers",
      icon: GraduationCap,
      path: "/admin/seekers",
      pattern: "/admin/seekers/*",
      type: "supLink",
      permissions: [Permission_Keys.Admin_JobSeekers_ViewJobSeekerProfile],
    },
    {
      id: 23,
      label: "Medicova Team",
      icon: UserCog,
      path: "/admin/employees",
      pattern: "/admin/employees/*",
      type: "supLink",
      permissions: [Permission_Keys.Admin_Employees_EditEmployee],
    },
    {
      id: 4,
      label: "Jobs",
      icon: HomeOutlined,
      path: "/admin/jobs",
      permissions: [Permission_Keys.Admin_Jobs_ViewJob],
    },
    {
      id: 5,
      label: "Applications",
      icon: HomeOutlined,
      path: "/admin/applications",
      permissions: [Permission_Keys.Admin_Applicants_ViewApplicants],
    },
    {
      id: 6,
      label: "Blog",
      icon: Newspaper,
      type: "collapse",
      permissions: [Permission_Keys.Admin_Blogs_Articles_ViewBlogArticle],
      links: [
        {
          id: 61,
          label: "Create New Blog",
          icon: FilePlus2,
          path: "/admin/blog/new",
          target: "_blank",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Blogs_Articles_AddBlogArticle],
        },
        {
          id: 62,
          label: "All Blogs",
          icon: NewspaperOutlined,
          path: "/admin/blog",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Blogs_Articles_ViewBlogArticle],
        },
        {
          id: 63,
          label: "Blog Settings",
          icon: SettingsOutlined,
          path: "/admin/blog/settings",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Blogs_Categories_ViewBlogCategory,
          ],
        },
      ],
    },
    {
      id: 7,
      label: "Finance",
      icon: CreditCard,
      type: "collapse",
      permissions: [Permission_Keys.Admin_Finance_ViewFinanceOverview],
      links: [
        {
          id: 71,
          label: "Transactions",
          icon: FilePlus2,
          path: "/admin/transactions",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_ViewTransactionHistory],
        },
        {
          id: 72,
          label: "Billing & Subscription",
          icon: NewspaperOutlined,
          path: "/admin/plans",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Finance_CreatePlan,
            Permission_Keys.Admin_Finance_EditPlan,
            Permission_Keys.Admin_Finance_DeletePlan,
          ],
        },
      ],
    },
    {
      id: 8,
      label: "Invoice",
      icon: Newspaper,
      type: "collapse",
      permissions: [Permission_Keys.Admin_Finance_ViewPaymentHistory],
      links: [
        {
          id: 81,
          label: "List",
          icon: FilePlus2,
          path: "/admin/invoices",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_ViewPaymentHistory],
        },
        {
          id: 82,
          label: "Add New",
          icon: SettingsOutlined,
          path: "/admin/invoices/create",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_AddInvoice],
        },
      ],
    },
    {
      id: 16,
      label: "Ads Management",
      icon: BarChart3,
      type: "collapse",
      permissions: [],
      links: [
        {
          id: 161,
          label: "Dashboard",
          icon: BarChart3,
          path: "/admin/ads",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_ViewPaymentHistory],
        },
        {
          id: 162,
          label: "Campaigns",
          icon: Megaphone,
          path: "/admin/ads/campaigns",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_ViewPaymentHistory],
        },
        {
          id: 163,
          label: "Add Campaign",
          icon: Plus,
          path: "/admin/ads/create",
          type: "supLink",
          permissions: [Permission_Keys.Admin_Finance_ViewPaymentHistory],
        },
      ],
    },
    {
      id: 9,
      label: "Report",
      icon: DescriptionOutlined,
      permissions: [Permission_Keys.Admin_Jobs_ViewJobAnalytics],
    },
    {
      id: 10,
      label: "Chat",
      icon: MessageOutlined,
      path: "/chat",
      type: "chat",
      notifications: 3,
      permissions: [Permission_Keys.Admin_JobSeekers_ChatWithJobSeekers],
    },
    {
      id: 11,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      type: "notification",
      notifications: 4,
      permissions: [Permission_Keys.Admin_Communications_ViewCommunicationLogs],
    },
    {
      id: 12,
      type: "text",
      section: "Settings",
      permissions: [],
    },
    {
      id: 13,
      label: "Site Settings",
      icon: Settings,
      type: "collapse",
      permissions: [Permission_Keys.Admin_Settings_ConfigurePlatformFeatures],
      links: [
        {
          id: 131,
          label: "Content",
          icon: FilePlus2,
          path: "/admin/site-settings/content",
          pattern: "/admin/site-settings/content/*",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Settings_ConfigurePlatformFeatures,
          ],
        },
        {
          id: 132,
          label: "Branding",
          icon: SettingsOutlined,
          path: "/admin/site-settings/branding",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Settings_ConfigurePlatformFeatures,
          ],
        },
        {
          id: 133,
          label: "SEO Manager",
          icon: Search,
          path: "/admin/site-settings/seo",
          pattern: "/admin/site-settings/seo/*",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Settings_ConfigurePlatformFeatures,
          ],
        },
        {
          id: 134,
          label: "Snippets",
          icon: DescriptionOutlined,
          path: "/admin/site-settings/snippets",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Settings_ConfigurePlatformFeatures,
          ],
        },
        {
          id: 135,
          label: "Tools",
          icon: ToolCase,
          path: "/admin/site-settings/tools",
          type: "supLink",
          permissions: [
            Permission_Keys.Admin_Settings_ConfigurePlatformFeatures,
          ],
        },
      ],
    },
    {
      id: 14,
      label: "Settings",
      icon: Settings,
      path: "/admin/settings",
      pattern: "/admin/settings/*",
      permissions: [Permission_Keys.Admin_Settings_ConfigurePlatformFeatures],
    },
    {
      id: 15,
      label: "Help Center",
      icon: HelpOutline,
      permissions: [],
    },
  ],
  default: [],
  employer: [
    {
      id: 0,
      type: "profile",
      pattern: "/co/[id]",
      permissions: [],
    },
    {
      id: 1,
      label: "Dashboard",
      icon: HomeOutlined,
      path: "/employer/dashboard",
      permissions: [
        Permission_Keys.Employer_ManageJobs,
        Permission_Keys.Employer_ManagePayments,
        Permission_Keys.Employer_ManageJobSeekerFolders,
      ],
    },
    {
      id: 2,
      label: "Company Info",
      icon: BusinessOutlined,
      path: "/employer/company-info",
      permissions: [Permission_Keys.Employer_ManageCompanySettings],
    },
    {
      id: 3,
      label: "Jobs",
      icon: WorkOutline,
      type: "collapse",
      permissions: [Permission_Keys.Employer_ManageJobs],
      links: [
        {
          id: 4,
          label: "Manage Jobs",
          icon: WorkOutline,
          path: "/employer/job/manage-jobs",
          pattern: "/employer/job/manage-jobs/*",
          type: "supLink",
          permissions: [Permission_Keys.Employer_ManageJobs],
        },
        {
          id: 5,
          label: "Post New Job",
          icon: PostAddOutlined,
          path: "/employer/job/posted",
          pattern: "/employer/job/posted/*",
          type: "supLink",
          permissions: [Permission_Keys.Employer_ManageJobs],
        },
      ],
    },
    {
      id: 7,
      label: "Search",
      icon: Search,
      type: "collapse",
      permissions: [Permission_Keys.Employer_InteractWithJobSeekers],
      links: [
        {
          id: 8,
          label: "Search",
          icon: Search,
          path: "/employer/search",
          type: "supLink",
          permissions: [Permission_Keys.Employer_InteractWithJobSeekers],
        },
        {
          id: 10,
          label: "My Folders",
          icon: FolderOutlined,
          path: "/employer/search/saved-search",
          pattern: "/employer/search/saved-search/*",
          type: "supLink",
          permissions: [Permission_Keys.Employer_ManageJobSeekerFolders],
        },
      ],
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: CreditCard,
      path: "/employer/billing",
      permissions: [Permission_Keys.Employer_ManagePayments],
    },
    {
      id: 111,
      label: "Upgrade Plan",
      icon: PaidOutlined,
      path: "/plans",
      permissions: [Permission_Keys.Employer_ManagePayments],
    },
    {
      id: 12,
      label: "Report",
      icon: DescriptionOutlined,
      permissions: [Permission_Keys.Employer_ManageJobs],
    },
    {
      id: 13,
      label: "Chat",
      icon: MessageOutlined,
      path: "/chat",
      type: "chat",
      notifications: 3,
      permissions: [Permission_Keys.Employer_InteractWithJobSeekers],
    },
    {
      id: 40,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      type: "notification",
      notifications: 4,
      permissions: [Permission_Keys.Employer_ManageJobApplications],
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
      permissions: [],
    },
    {
      id: 16,
      label: "Settings",
      icon: SettingsOutlined,
      path: "/employer/setting",
      pattern: "/employer/setting/*",
      permissions: [],
    },
    {
      id: 17,
      label: "Help Center",
      icon: HelpOutline,
      permissions: [],
    },
  ],
  unEmployee: [
    {
      id: 2,
      label: "Company Info",
      icon: BusinessOutlined,
      path: "/employer/company-info",
      permissions: [Permission_Keys.Employer_ManageCompanySettings],
    },
  ],
  seeker: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
      permissions: [],
    },
    // {
    //   id: 18,
    //   icon: HomeOutlined,
    //   label: "Home",
    //   path: "/",
    // },
    {
      id: 20,
      icon: MessageOutlined,
      label: "Messages",
      type: "chat",
      path: "/chat",
      notifications: 3,
      permissions: [],
    },
    {
      id: 21,
      icon: DescriptionOutlined,
      label: "My Applications",
      path: "/job-seeker/my-applications",
      permissions: [],
    },
    {
      id: 22,
      icon: Search,
      label: "Find Jobs",
      path: "/a/explore",
      pattern: "/a/*",
      permissions: [],
    },
    {
      id: 222,
      icon: BookMarked,
      label: "Saved Jobs",
      type: "savedJobs",
      path: "/job-seeker/saved-jobs",
      permissions: [],
    },
    {
      id: 23,
      icon: BusinessOutlined,
      label: "Browse Companies",
      path: "/job-seeker/browse-companies",
      permissions: [],
    },
    {
      id: 24,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      type: "notification",
      notifications: 4,
      permissions: [],
    },

    {
      id: 26,
      section: "Settings",
      type: "text",
      permissions: [],
    },
    {
      id: 27,
      icon: SettingsOutlined,
      label: "Settings",
      path: "/job-seeker/setting",
      pattern: "/job-seeker/setting/*",
      permissions: [],
    },
    {
      id: 28,
      icon: HelpOutline,
      label: "Help Center",
      path: "#",
      permissions: [],
    },
  ],
  unverified: [
    {
      id: 0,
      label: "Verify Account",
      icon: MessageOutlined,
      notifications: 1,
      path: "/auth/verify",
      pattern: "/auth/verify",
      permissions: [],
    },
  ],
};
