import {
  Addon,
  Feature,
  PlansReport,
  SubscriptionPlan,
  TransactionType,
} from "../types/finance";

export const TOP_REVENUE_PLANS: PlansReport[] = [
  {
    id: "1",
    name: "Business",
    price: 26000,
    purchases: 50,
    employers: 30,
    revenue: 50 * 26000, // 1,300,000 EGP
    status: "active",
  },
  {
    id: "2",
    name: "Pro",
    price: 5500,
    purchases: 120,
    employers: 100,
    revenue: 120 * 5500, // 660,000 EGP
    status: "active",
  },
  {
    id: "3",
    name: "Basic",
    price: 3500,
    purchases: 180,
    employers: 100,
    revenue: 180 * 3500, // 630,000 EGP
    status: "active",
  },
  {
    id: "4",
    name: "Free",
    price: 0,
    purchases: 700,
    employers: 300,
    revenue: 0, // 630,000 EGP
    status: "active",
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: "4",
    name: "Free",
    description: "Start for free and explore basic features",
    highlight: false,
    badge: "Free Forever",
    duration: 1,
    price: 0,
    vat: 20,
    vatDescription: "No VAT — this plan is completely free.",
    currency: "EGP",
    discountedPrice: 0,
    features: [
      { name: "Unlimited Profile Views", tag: "new" },
      { name: "10 Candidate Unlocks" },
      { name: "1 Job Posting" },
      { name: "1 User Seat" },
      {
        name: "Access unlocked profiles for 1 month extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 10,
    jobs: 1,
    invitations: 5,
    users: 1,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 1,
  },
  {
    id: "3",
    name: "Basic",
    description: "Ideal for small teams with light hiring needs",
    highlight: false,
    duration: 1,
    price: 3990,
    discountedPrice: 3500,
    vat: 14,
    vatDescription:
      "Subtotal: EGP 3,500\nVAT (14%): EGP 490\nTotal: EGP 3,990 (inclusive of VAT)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views" },
      { name: "30 Candidate Unlocks" },
      { name: "5 Job Postings", tag: "new" },
      { name: "2 User ", tag: "new" },
      {
        name: "Access unlocked profiles for 1 month extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 30,
    jobs: 5,
    invitations: 10,
    users: 2,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 1,
  },
  {
    id: "2",
    name: "Pro",
    description: "Perfect for companies hiring 1–2 roles monthly",
    highlight: false,
    badge: "Most Popular",
    vat: 20,
    duration: 6,
    price: 6270,
    discountedPrice: 5500,
    vatDescription:
      "Subtotal: EGP 5,500\nVAT (14%): EGP 770\nTotal: EGP 6,270 (includes all taxes)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views" },
      { name: "150 Candidate Unlocks" },
      { name: "20 Job Postings", tag: "new" },
      { name: "3 User " },
      { name: "Priority Support", tag: "new" },
      {
        name: "Access unlocked profiles for 3 months extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 150,
    jobs: 20,
    invitations: 60,
    users: 3,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 3,
  },
  {
    id: "1",
    name: "Business",
    description: "Designed for teams with active or high-volume hiring",
    highlight: true,
    badge: "Best Value",
    vat: 20,
    duration: 12,
    price: 29640,
    discountedPrice: 26000,
    vatDescription:
      "Subtotal: EGP 26,000\nVAT (14%): EGP 3,640\nTotal Payable: EGP 29,640 (all-inclusive)",
    currency: "EGP",
    features: [
      { name: "Unlimited Profile Views", tag: "new" },
      { name: "400 Candidate Unlocks" },
      { name: "30 Job Postings" },
      { name: "10 User " },
      { name: "Featured & Premium Support" },
      {
        name: "Access unlocked profiles for 6 months extra after plan expiration",
      },
    ],
    views: Infinity,
    unlocks: 400,
    jobs: 30,
    invitations: 150,
    users: 10,
    status: "active",
    created_at: "2022-01-01",
    extraAccess: 6,
  },
];

export const TRANSACTIONS: TransactionType[] = [
  {
    id: "1",
    invoice_id: "INV_2025_001",
    created_at: "13 July, 2021",
    payment_method: "VISA",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Jack",
    },
    total_amount: 29.99,
    download_receipt_url: "",
  },
  {
    id: "2",
    invoice_id: "INV_2025_002",
    created_at: "13 July, 2021",
    payment_method: "PayPal",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Sarah",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "3",
    invoice_id: "INV_2025_003",
    created_at: "22 September, 2021",
    payment_method: "VISA",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Mike",
    },
    total_amount: 19.99,
    download_receipt_url: "",
  },
  {
    id: "4",
    invoice_id: "INV_2025_004",
    created_at: "30 October, 2021",
    payment_method: "PayPal",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Emma",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "5",
    invoice_id: "INV_2025_005",
    created_at: "5 November, 2021",
    payment_method: "MasterCard",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Liam",
    },
    total_amount: 39.99,
    download_receipt_url: "",
  },
  {
    id: "6",
    invoice_id: "INV_2025_006",
    created_at: "15 December, 2021",
    payment_method: "Stripe",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Sophia",
    },
    total_amount: 14.99,
    download_receipt_url: "",
  },
  {
    id: "7",
    invoice_id: "INV_2025_007",
    created_at: "3 January, 2022",
    payment_method: "VISA",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Oliver",
    },
    total_amount: 9.99,
    download_receipt_url: "",
  },
  {
    id: "8",
    invoice_id: "INV_2025_008",
    created_at: "20 February, 2022",
    payment_method: "PayPal",
    type: "subscription",
    planId: "2",
    plan: "Pro",
    employer: {
      username: "#",
      image: "",
      name: "Ava",
    },
    total_amount: 24.99,
    download_receipt_url: "",
  },
  {
    id: "9",
    invoice_id: "INV_2025_009",
    created_at: "10 March, 2022",
    payment_method: "Bank Transfer",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Ethan",
    },
    total_amount: 49.99,
    download_receipt_url: "",
  },
  {
    id: "10",
    invoice_id: "INV_2025_010",
    created_at: "25 April, 2022",
    payment_method: "Stripe",
    type: "add-on",
    planId: "",
    plan: "",
    employer: {
      username: "#",
      image: "",
      name: "Isabella",
    },
    total_amount: 19.99,
    download_receipt_url: "",
  },
  {
    id: "11",
    invoice_id: "INV_2025_011",
    created_at: "12 May, 2022",
    payment_method: "MasterCard",
    type: "subscription",
    planId: "1",
    plan: "Business",
    employer: {
      username: "#",
      image: "",
      name: "Noah",
    },
    total_amount: 39.99,
    download_receipt_url: "",
  },
  {
    id: "12",
    invoice_id: "INV_2025_012",
    created_at: "8 June, 2022",
    payment_method: "VISA",
    type: "subscription",
    planId: "3",
    plan: "Basic",
    employer: {
      username: "#",
      image: "",
      name: "Mia",
    },
    total_amount: -9.99,
    download_receipt_url: "",
  },
];

export const ADDONS_DATA: Addon[] = [
  {
    id: "addon_001",
    name: "Premium Unlocks",
    description: "Get 10 extra candidate unlocks to access top profiles.",
    price: 20,
    vatPercent: 10,
    discountPercent: 0,
    totalPrice: 22, // 20 + 10% VAT
    currency: "USD",
    badge: "Popular",
    isHighlighted: true,
    status: "active",
    active: true,
    isHistorical: false,
    features: {
      unlocks: 10,
    },
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2025-09-01T10:00:00Z",
  },
  {
    id: "addon_002",
    name: "Starter Bundle",
    description: "Perfect for small teams: 5 Jobs + 100 Unlocks.",
    price: 50,
    vatPercent: 10,
    discountPercent: 5,
    totalPrice: 52.25, // (50 - 5%) + 10% VAT
    currency: "USD",
    badge: "Starter Pack",
    isHighlighted: false,
    status: "active",
    active: true,
    isHistorical: false,
    features: {
      jobs: 5,
      unlocks: 100,
    },
    createdAt: "2025-09-02T09:00:00Z",
    updatedAt: "2025-09-02T09:00:00Z",
  },
  {
    id: "addon_003",
    name: "Pro Hiring Pack",
    description: "20 Job posts + 200 Unlocks + 50 Invites.",
    price: 150,
    vatPercent: 10,
    discountPercent: 20,
    totalPrice: 132, // (150 - 20%) + 10% VAT
    currency: "USD",
    badge: "Best Value",
    isHighlighted: true,
    status: "active",
    active: true,
    isHistorical: false,
    features: {
      jobs: 20,
      unlocks: 200,
      invites: 50,
    },
    createdAt: "2025-09-03T11:30:00Z",
    updatedAt: "2025-09-03T11:30:00Z",
  },
  {
    id: "addon_004",
    name: "Legacy Unlocks",
    description: "Old version of unlock package (replaced).",
    price: 15,
    vatPercent: 10,
    discountPercent: 0,
    totalPrice: 16.5,
    currency: "USD",
    badge: undefined,
    isHighlighted: false,
    status: "historical",
    active: false,
    isHistorical: true,
    features: {
      unlocks: 5,
    },
    createdAt: "2025-08-10T08:00:00Z",
    updatedAt: "2025-09-01T09:00:00Z",
  },
  {
    id: "addon_005",
    name: "Summer Promo Pack",
    description: "Special offer pack for the summer campaign.",
    price: 80,
    vatPercent: 10,
    discountPercent: 30,
    totalPrice: 61.6, // (80 - 30%) + 10% VAT
    currency: "USD",
    badge: "Limited",
    isHighlighted: true,
    status: "inactive",
    active: false,
    isHistorical: false,
    features: {
      jobs: 10,
      unlocks: 50,
      invites: 20,
    },
    createdAt: "2025-06-01T12:00:00Z",
    updatedAt: "2025-08-01T12:00:00Z",
  },
  {
    id: "addon_006",
    name: "Deleted Test Addon",
    description:
      "This addon was deleted but remains linked to past transactions.",
    price: 25,
    vatPercent: 10,
    discountPercent: 0,
    totalPrice: 27.5,
    currency: "USD",
    badge: undefined,
    isHighlighted: false,
    status: "deleted",
    active: false,
    isHistorical: true,
    features: {
      jobs: 2,
    },
    createdAt: "2025-05-01T10:00:00Z",
    updatedAt: "2025-07-01T10:00:00Z",
  },
];

export const DUMMY_FEATURES: Feature[] = [
  {
    id: "feature_unlocks",
    name: "Unlocks",
    description: "Access job seeker profiles.",
    unit: "per unlock",
    isActive: true,
    currency: "EGP",
    tiers: [
      { min: 1, max: 10, unitPrice: 2 },
      { min: 11, max: 20, unitPrice: 1.5 },
      { min: 21, max: 50, unitPrice: 1 },
    ],
  },
  {
    id: "feature_users",
    name: "Users",
    description: "Number of team members who can access the platform.",
    unit: "per user",
    isActive: true,
    currency: "EGP",
    tiers: [
      { min: 1, max: 5, unitPrice: 10 },
      { min: 6, max: 10, unitPrice: 8 },
      { min: 11, max: 20, unitPrice: 6 },
    ],
  },
  {
    id: "feature_jobs",
    name: "Jobs",
    description: "Number of job posts you can publish.",
    unit: "per job post",
    isActive: true,
    currency: "EGP",
    tiers: [
      { min: 1, max: 5, unitPrice: 5 },
      { min: 6, max: 15, unitPrice: 4 },
      { min: 16, max: 30, unitPrice: 3 },
    ],
  },
  {
    id: "feature_invites",
    name: "Invites",
    description: "Invite job seekers to apply for your roles.",
    unit: "per invite",
    isActive: true,
    currency: "EGP",
    tiers: [
      { min: 1, max: 20, unitPrice: 1 },
      { min: 21, max: 50, unitPrice: 0.8 },
      { min: 51, max: 100, unitPrice: 0.6 },
    ],
  },
  {
    id: "feature_views",
    name: "Views",
    description: "Number of views on job posts.",
    unit: "per 100 views",
    isActive: true,
    currency: "EGP",
    tiers: [
      { min: 1, max: 5, unitPrice: 3 },
      { min: 6, max: 15, unitPrice: 2.5 },
      { min: 16, max: 30, unitPrice: 2 },
    ],
  },
];
