export enum EducationLevel {
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  TECH_INSTITUE = 'TECH_INSTITUE',
  BACHELORS = 'BACHELORS',
  DIPLOMA = 'DIPLOMA',
  MASTERS = 'MASTERS',
  DOCTORATE = 'DOCTORATE',
  FELLOWSHIP = 'FELLOWSHIP',
}